name: frpclib

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Title"
        required: true
        default: "Build FrpcLib"

env:
  GO_VERSION: '1.22'
  GOMOBILE_COMMIT: 'latest'
  NDK_LTS_VERSION: '25.1.8937393'
  SDK_TOOLS_VERSION: '9477386'
  ANDROID_PLATFORM_VERSION: '33'
  ANDROID_BUILD_TOOLS_VERSION: '33.0.1'
  MIN_ANDROID_API: '21'

jobs:
  frpclib:
    name: Build FrpcLib
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 列出项目目录，帮助确认 frpclib 的确切位置
      - name: List directory structure
        run: ls -R

      - run: sudo apt-get update -q -y
      - run: sudo apt-get install -q -y --no-install-recommends curl wget unzip g++ libc6-dev

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download & install the Android SDK.
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - run: sdkmanager --update
      - run: sdkmanager 'platforms;android-${{ env.ANDROID_PLATFORM_VERSION }}'
      - run: sdkmanager 'build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}'
      - run: sdkmanager 'ndk;${{ env.NDK_LTS_VERSION }}'
      - run: sdkmanager 'extras;android;m2repository'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go install golang.org/x/mobile/cmd/gomobile@${{ env.GOMOBILE_COMMIT }}
      - run: go install golang.org/x/mobile/cmd/gobind@${{ env.GOMOBILE_COMMIT }}
      - run: gomobile init -v

      - run: go mod tidy && go get -u golang.org/x/mobile/bind

      # 这里使用路径占位符，根据目录结构调整
      - name: Build FrpcLib
        run: cd <adjusted_path_to_frpc> && gomobile bind -v --target=android -androidapi ${{ env.MIN_ANDROID_API }} -o frpclib.aar -ldflags="-s -w" .

      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FrpcLib
          path: cmd/frpclib/frpclib*
          if-no-files-found: error
